# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogoUnidades',
            new_name='Unidad',
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Catalogo Unidad', 'verbose_name_plural': 'Catalogo Unidades'},
        ),
        migrations.RemoveField(
            model_name='entradas',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CatalogoCategoria',
        ),
    ]
