# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 04:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170206_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
